name: Java CI & Docker Build

# Kích hoạt khi có push lên branch 'master'
on:
  push:
    branches: [ master ]
  # release:
  #   types: [created]

jobs:
  # ----------------------------------------------------------------------------------
  # JOB 1: BUILD và TEST Java (CI)
  # ----------------------------------------------------------------------------------
  build_test_jar:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        server-id: github
        settings-path: ${{ github.workspace }}

    - name: Build with Maven
      run: mvn -B package --file pom.xml
    
  # ----------------------------------------------------------------------------------
  # JOB 2: BUILD và PUSH Docker Image (CI)
  # ----------------------------------------------------------------------------------
  build_and_push_docker:
    needs: build_test_jar 
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
      
    - name: Set up Docker Metadata (Tags)
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ghcr.io/${{ github.repository }} 
        tags: |
          type=sha,format=long,prefix=

    - name: Log in to GHCR
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Build and Push Docker Image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}

  # ----------------------------------------------------------------------------------
  # JOB 3: CẬP NHẬT GITOPS MANIFEST (CD - Kích hoạt Argo CD)
  # ----------------------------------------------------------------------------------
  update_k8s_manifest:
    needs: build_and_push_docker 
    runs-on: ubuntu-latest
    
    # Cần quyền 'contents: write' để đẩy thay đổi GitOps trở lại repo
    permissions:
      contents: write 

    steps:
    - name: Checkout Code
      # Lấy toàn bộ lịch sử để có thể commit/push
      uses: actions/checkout@v4
      with:
        fetch-depth: 0 
        
    - name: Cập nhật Image Tag trong Manifest
      run: |
        # 1. Định nghĩa đường dẫn Image SHA mới
        IMAGE_SHA="ghcr.io/${{ github.repository }}:${{ github.sha }}"
        
        # 2. Thực hiện thay thế Tag Placeholder 'latest' bằng SHA commit mới
        # Đây là lệnh SED chính xác dựa trên file deployment.yaml của bạn
        sed -i "s|image: ghcr.io/Erige005/giua-ki:latest|image: $IMAGE_SHA|g" k8s/deployment.yaml
        
    - name: Commit và Đẩy thay đổi K8s Manifest (Kích hoạt Argo CD)
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: 'CD: Update image tag to ${{ github.sha }} for Argo CD'
        files: k8s/deployment.yaml
        commit_options: '--no-verify --author="github-actions[bot] <github-actions[bot]@users.noreply.github.com>"'