name: Java CI & Docker Build

# 1. THAY ĐỔI: Kích hoạt khi có push lên branch 'main' (để dễ test CI)
on:
  push:
    branches: [ master ]
  # Giữ lại trigger 'release' nếu bạn muốn
  # release:
  #   types: [created]

jobs:
  # JOB 1: BUILD và TEST Java (Giữ lại logic của bạn)
  build_test_jar:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        # Các tham số Maven của bạn
        server-id: github
        settings-path: ${{ github.workspace }}

    - name: Build with Maven
      # Thay đổi lệnh mvn deploy thành mvn package vì deploy sẽ thực hiện ở Job Docker
      run: mvn -B package --file pom.xml
      
    # BỎ qua bước Publish Maven Package tại đây (trừ khi bạn thực sự cần)
    
  # ----------------------------------------------------------------------------------
  # JOB 2: BUILD và PUSH Docker Image (Mục tiêu chính)
  # ----------------------------------------------------------------------------------
  build_and_push_docker:
    # Đảm bảo job này chỉ chạy sau khi Job 1 (Build và Test) thành công
    needs: build_test_jar 
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write # Cần quyền này để đẩy Image lên GHCR

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
      
    - name: Set up Docker Metadata (Tags)
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ghcr.io/${{ github.repository }} 
        # Sử dụng SHA của commit làm tag (dễ truy vết cho K8s)
        tags: |
          type=sha,format=long,prefix=

    - name: Log in to GHCR
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }} # Sử dụng token mặc định của GitHub
        
    - name: Build and Push Docker Image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}